### PR TITLE
Update doctr to 1.4.0

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
What? Why is AppVeyor failing?

**Comment by asmeurer** [comment]
Might just merge this anyways. Windows support isn't that important. We really need the Linux build, as that's what's installed on Travis.

**Comment by ocefpaf** [comment]
> If you re-render it will fix the failure. (There will be a failure on Travis-CI too)

What? Why is AppVeyor failing?

> Might just merge this anyways. Windows support isn't that important. We really need the Linux build, as that's what's installed on Travis.

How about Windows users setting it up locally? There are some out there and you just excluded them from using latest `doctr` :stuck_out_tongue_closed_eyes:

**Comment by asmeurer** [comment]
Yes, I know Windows locally is important. But doctr is failing on Travis without this release, hence my urgency to get the Linux build out there. 

I'll try a rerender.

**Comment by asmeurer** [comment]
By the way, bug with conda smithy. It didn't `git add` the permissions fix for the meta.yaml when I ran `rerender`.

**Comment by ocefpaf** [comment]
> By the way, bug with conda smithy. It didn't `git add` the permissions fix for the meta.yaml when I ran `rerender`. 

Please report that in the `conda-smithy` repo: https://github.com/conda-forge/conda-smithy

I am not up to date with the many new releases that were all self-merged. I still use an old version that has only bugfixes.

**Comment by asmeurer** [comment]
There seems to be some work around that already here https://github.com/conda-forge/conda-smithy/pull/379

**Pull request merged**
