### PR TITLE
Update doctr to 1.1.1

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
Hmm, that's not what I was expecting. The build scripts always upload the package to conda forge? I would expect it to only do so on master. CC @conda-forge-manager

**Comment by jakirkham** [comment]
> Hmm, that's not what I was expecting. The build scripts always upload the package to conda forge?

Yep. That's why one must fork. The idea is other branches could represent other versions or builds with special features.

FYI `conda-forge-manager` is a bot. Better to use `conda-forge/core`.

**Comment by jakirkham** [comment]
A good example of multiple versions might be [numpy](https://github.com/conda-forge/numpy-feedstock/branches) or [python](https://github.com/conda-forge/python-feedstock/branches).

**Comment by asmeurer** [comment]
> Yep. That's why one must fork. The idea is other branches could represent other versions or builds with special features.

Do I have any recourse? As soon as I merge this it will fail, because the package is already uploaded.

> FYI conda-forge-manager is a bot. Better to use conda-forge/core.

You should add a description to that. You might also rename it to @conda-forge-core, as that will appear in the top of the completions (and anyway, is `core` a package?).

**Comment by asmeurer** [comment]
Another question for @conda-forge/core, is it possible to enable branch protection on my feedstocks? I don't seem to have admin access for them.

**Comment by asmeurer** [comment]
I guess I can merge this and then bump the build number (in a proper PR).

**Comment by jakirkham** [comment]
> Do I have any recourse? As soon as I merge this it will fail, because the package is already uploaded.

Actually it won't fail. It just won't do anything.

> > FYI conda-forge-manager is a bot. Better to use conda-forge/core.
> 
> You should add a description to that.

From the bot's [about](https://github.com/conda-forge-manager).

`Please ping @conda-forge/core to contact.`

Though if you have better ideas for where to place that info please let us know.

> You might also rename it to @conda-forge-core, as that will appear in the top of the completions

Wouldn't that be more confusing? Anyways I don't think any of us were thinking to hard about names. We were just eager to solve a GitHub API problem that was becoming very painful.

> (and anyway, is `core` a package?).

I hope not. 😟 We did capitalize it so it is `Core` technically, but I don't know if GitHub would respect that distinction.

> Another question for @conda-forge/core, is it possible to enable branch protection on my feedstocks?

I think everyone just has write permissions. Don't know the whole history behind it. There may be a reason that admin is not granted universal. I can guess a few.

This isn't exactly the same thing, but we have discussed requiring explicit listing of release branches. See issue ( https://github.com/conda-forge/conda-forge.github.io/issues/87 ). Sounds like we are agreed, but no one has had time to do it.

**Comment by jakirkham** [comment]
Sorry I tried to respond to all of your question, but I kept adding to it so it took a bit.

**Comment by asmeurer** [comment]
> From the bot's about.

I mean if you type @conda-forge in the completions it has descriptions for each of the users, but for @conda-forge-manager it just says `conda-forge-manager`. Not sure where that text comes from. 

> I think everyone just has write permissions. Don't know the whole history behind it. There may be a reason that admin is not granted universal. I can guess a few.

I'm happy to not have admin, but I do want branch protection enabled.

**Comment by asmeurer** [comment]
> Actually it won't fail. It just won't do anything.

Seems the wrong behavior to me.

**Comment by jakirkham** [comment]
> > From the bot's about.
> 
> I mean if you type @conda-forge in the completions it has descriptions for each of the users, but for @conda-forge-manager it just says `conda-forge-manager`. Not sure where that text comes from.

I think those descriptions are coming from the teams descriptions. Though if there is a way to do it for users that sounds like a good idea. It may be a GitHub request type thing. If there is something we can do on our end, that would be great.

> > I think everyone just has write permissions. Don't know the whole history behind it. There may be a reason that admin is not granted universal. I can guess a few.
> 
> I'm happy to not have admin, but I do want branch protection enabled. 

Could you please raise an issue at [`conda-smithy`](https://github.com/conda-forge/conda-smithy)?

> > Actually it won't fail. It just won't do anything.
> 
> Seems the wrong behavior to me.

It's not replacing the packages that are already up there.

Sometimes we need to re-run if an upload failed. This isn't a frequent issue, but it does happen. Certainly wouldn't want this to error on CircleCI for me because a Python 2.7 package is already uploaded when I need to get to the Python 3.5 package built and uploaded.

**Pull request merged**
