### PR TITLE
1.6.0

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
What is going on with AppVeyor? I'm going to ignore that, because Windows support isn't that important.

**Comment by ocefpaf** [comment]
@asmeurer let's try to make this `noarch`.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by asmeurer** [comment]
Wait why did this not actually build? @ocefpaf

**Comment by ocefpaf** [comment]
No idea :confused: 

Anyways, there is a pre-selector there for py>=35 so noarch is not OK in those cases yet.

**Pull request merged**
