### PR TITLE
Update to 1.6.1

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
@conda-forge-admin, please remove noarch: python

**Comment by asmeurer** [comment]
Guess that doesn't work. And I can't rerender locally:

```pytb
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 290, in main
    args.subcommand_func(args)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 194, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 722, in main
    render_circle(env, config, forge_dir)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 72, in render_circle
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 221, in fudge_subdir
    build_config.subdir = subdir
AttributeError: can't set attribute
```

Since 1.6.0 didn't actually build, I guess this doesn't need to be fixed right NOW, but it should be fixed soon. I'll wait until tomorrow to see if anyone has a brilliant solution. Otherwise, I'll just revert the robot commits.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
You may need to upgrade `conda-smithy` in your system. Things worked fine for me, but you can remove the `noarch` line, like I did, and use the bot to re-render for you. Let's see if that works here...

**Comment by asmeurer** [comment]
I updated conda-smithy right before running the command.

**Pull request merged**
