### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by jakirkham** [comment]
How did the `meta.yaml` file's permission's change?

**Comment by asmeurer** [comment]
The rerender command changed it (but it didn't git add it).

**Comment by jakirkham** [comment]
Thanks @asmeurer .

That's rather strange though as we don't generally change permissions on files. There are only two files we do that with both in `ci_support`. Further when re-rendering we now stage all changes that are part of the re-rendering. Finally re-rendering only touches the CI support files and not the `recipe` directory.

Is this something that you can reproduce? If so, it would be nice to get more info.

**Comment by asmeurer** [comment]
Maybe it was a result of something else. I also just edited the meta.yaml in another branch before doing the rerender.

**Comment by jakirkham** [comment]
As for the permission issues, I encountered a similar issue recently that I was able to reproduce. These are probably both related to `conda-smithy` issue ( https://github.com/conda-forge/conda-smithy/issues/365 ). PR ( https://github.com/conda-forge/conda-smithy/pull/383 ) fixed it for me. This is available as `conda-smithy` version `1.5.3`.

**Pull request merged**
